spring.datasource.url: jdbc:mysql://localhost:3306/tasklist?serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: testtest
spring.jpa.hibernate.ddl-auto: update
someParameter: 1234